export const kraActionTypes = {
	ADD_PROJECT_ADVERTISEMENT: 'ADD_PROJECT_ADVERTISEMENT',
	ADD_PROJECT_ADVERTISEMENT_LEAD: 'ADD_PROJECT_ADVERTISEMENT_LEAD',
	FETCH_PROJECT_ADVERTISEMENTS: 'FETCH_PROJECT_ADVERTISEMENTS',
	FETCH_PROJECT_ADVERTISEMENT_LEADS: 'FETCH_PROJECT_ADVERTISEMENT_LEADS',
	FETCH_PROJECT_ADVERTISEMENT_DETAILS: 'FETCH_PROJECT_ADVERTISEMENT_DETAILS',
	UPDATE_PROJECT_ADVERTISEMENT_DETAILS:
		'UPDATE_PROJECT_ADVERTISEMENT_DETAILS',
	DELETE_PROJECT_ADVERTISEMENT: 'DELETE_PROJECT_ADVERTISEMENT',
	TOGGLE_ADD_PROJECT_ADVERTISEMENT_LOADING:
		'TOGGLE_ADD_PROJECT_ADVERTISEMENT_LOADING',
	TOGGLE_ADD_PROJECT_ADVERTISEMENT_LEAD_LOADING:
		'TOGGLE_ADD_PROJECT_ADVERTISEMENT_LEAD_LOADING',
	TOGGLE_FETCH_PROJECT_ADVERTISEMENTS_LOADING:
		'TOGGLE_FETCH_PROJECT_ADVERTISEMENTS_LOADING',
	TOGGLE_FETCH_PROJECT_ADVERTISEMENT_LEADS_LOADING:
		'TOGGLE_FETCH_PROJECT_ADVERTISEMENT_LEADS_LOADING',
	TOGGLE_FETCH_PROJECT_ADVERTISEMENT_DETAILS_LOADING:
		'TOGGLE_FETCH_PROJECT_ADVERTISEMENT_DETAILS_LOADING',
	TOGGLE_UPDATE_PROJECT_ADVERTISEMENT_DETAILS_LOADING:
		'TOGGLE_UPDATE_PROJECT_ADVERTISEMENT_DETAILS_LOADING',
	TOGGLE_DELETE_PROJECT_ADVERTISEMENT_LOADING:
		'TOGGLE_DELETE_PROJECT_ADVERTISEMENT_LOADING',
};
