export const propertyActionTypes = {
	// Initiate fetching
	SEARCH_PROPERTY_START: 'SEARCH_PROPERTY_START',
	GET_PROPERTY_DETAILS_START: 'GET_PROPERTY_DETAILS_START',
	GET_PROPERTY_RESOURCES_START: 'GET_PROPERTY_RESOURCES_START',
	POST_PROPERTY_START: 'POST_PROPERTY_START',
	// set values
	SET_PROPERTY_RESOURCES: 'SET_PROPERTY_RESOURCES',
	// Toggle loading
	TOGGLE_SEARCH_PROPERTY_LOADING: 'TOGGLE_SEARCH_PROPERTY_LOADING',
	TOGGLE_GET_PROPERTY_DETAILS_LOADING: 'TOGGLE_GET_PROPERTY_DETAILS_LOADING',
	TOGGLE_GET_PROPERTY_RESOURCES_LOADING:
		'TOGGLE_GET_PROPERTY_RESOURCES_LOADING',
	TOGGLE_POST_PROPERTY_LOADING: 'TOGGLE_POST_PROPERTY_LOADING',
	// SetErrors
};
