export const propertyActionTypes = {
	// Initiate fetching
	SEARCH_PROPERTY_START: 'SEARCH_PROPERTY_START',
	GET_PROPERTY_DETAILS_START: 'GET_PROPERTY_DETAILS_START',
	// set values
	// Toggle loading
	TOGGLE_SEARCH_PROPERTY_LOADING: 'TOGGLE_SEARCH_PROPERTY_LOADING',
	TOGGLE_GET_PROPERTY_DETAILS_LOADING: 'TOGGLE_GET_PROPERTY_DETAILS_LOADING',
	// SetErrors
};
