export const SidebarActionTypes = {
	TOGGLE_PROPERTY_RENT: 'TOGGLE_PROPERTY_RENT',
	TOGGLE_PROPERTY_SALE: 'TOGGLE_PROPERTY_SALE',
	TOGGLE_LOCATION: 'TOGGLE_LOCATION',
	TOGGLE_PROJECT: 'TOGGLE_PROJECT',
};
