export const SidebarActionTypes = {
	TOGGLE_PROPERTY_RENT: 'TOGGLE_PROPERTY_RENT',
	TOGGLE_PROPERTY_SALE: 'TOGGLE_PROPERTY_SALE',
	TOGGLE_LOCATION: 'TOGGLE_LOCATION',
	TOGGLE_PROJECT: 'TOGGLE_PROJECT',
	TOGGLE_BUILDER: 'TOGGLE_BUILDER',
	TOGGLE_KRA: 'TOGGLE_KRA',
	TOGGLE_KPI: 'TOGGLE_KPI',
	TOGGLE_PACKAGE: 'TOGGLE_PACKAGE',
	TOGGLE_REVIEW: 'TOGGLE_REVIEW',
	TOGGLE_JOIN_REQUEST: 'TOGGLE_JOIN_REQUEST',
};
