export enum CpAuthActionType {
	CP_SIGN_IN_START = 'CP_SIGN_IN_START',
	CP_SIGN_IN_SUCCESS = 'CP_SIGN_IN_SUCCESS',
	CP_SET_USER = 'CP_SET_USER',
	CP_SIGN_IN_ERROR = 'CP_SIGN_IN_ERROR',
	CP_LOG_OUT = 'CP_LOG_OUT',
}
