export const queryActionTypes = {
	// Initiate fetching

	GET_QUERIES: 'GET_QUERIES',
	GET_EXPERT_QUERIES: 'GET_EXPERT_QUERIES',
	DELETE_QUERY: 'DELETE_QUERY',
	DELETE_EXPERT_QUERY: 'DELETE_EXPERT_QUERY',
	// set values
	SET_QUERIES: 'SET_QUERIES',
	SET_EXPERT_QUERIES: 'SET_EXPERT_QUERIES',

	// Toggle loading

	TOGGLE_GET_QUERIES_LOADING: 'TOGGLE_GET_QUERIES_LOADING',
	TOGGLE_GET_EXPERT_QUERIES_LOADING: 'TOGGLE_GET_EXPERT_QUERIES_LOADING',
	TOGGLE_DELETE_QUERY_LOADING: 'TOGGLE_DELETE_QUERY_LOADING',
	TOGGLE_DELETE_EXPERT_QUERY_LOADING: 'TOGGLE_DELETE_EXPERT_QUERY_LOADING',
	// SetErrors
};
