export const builderActionTypes = {
	ADD_BUILDER_START: 'ADD_BUILDER_START',
	TOGGLE_ADD_BUILDER_LOADING: 'TOGGLE_ADD_BUILDER_LOADING',
	FETCH_BUILDERS_START: 'FETCH_BUILDERS_START',
	SET_BUILDERS: 'SET_BUILDERS',
	TOGGLE_FETCH_BUILDERS_LOADING: 'TOGGLE_FETCH_BUILDERS_LOADING',
	UPDATE_BUILDER_START: 'UPDATE_BUILDER_START',
	TOGGLE_UPDATE_BUILDER_LOADING: 'TOGGLE_UPDATE_BUILDER_LOADING',
	FETCH_BUILDER_INFO_START: 'FETCH_BUILDER_INFO_START',
	TOGGLE_FETCH_BUILDER_INFO_LOADING: 'TOGGLE_FETCH_BUILDER_INFO_LOADING',
};
