export const authActionTypes = {
	// Initiate fetching
	SIGN_UP_START: 'SIGN_UP_START',
	SEND_OTP_START: 'SEND_OTP_START',
	VALIDATE_OTP_START: 'VALIDATE_OTP_START',
	SIGN_IN_START: 'SIGN_IN_START',
	// set values
	// Toggle loading
	TOGGLE_SIGN_UP_LOADING: 'TOGGLE_SIGN_UP_LOADING',
	TOGGLE_SEND_OTP_LOADING: 'TOGGLE_SEND_OTP_LOADING',
	TOGGLE_VALIDATE_OTP_LOADING: 'TOGGLE_VALIDATE_OTP_LOADING',
	TOGGLE_SIGN_IN_LOADING: 'TOGGLE_SIGN_IN_LOADING',
	// SetErrors
};
