export const projectActionTypes = {
	ADD_PROJECT_FLAT_START: 'ADD_PROJECT_FLAT_START',
	TOGGLE_ADD_PROJECT_FLAT_LOADING: 'TOGGLE_ADD_PROJECT_FLAT_LOADING',
	FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
	SET_PROJECTS: 'SET_PROJECTS',
	TOGGLE_FETCH_PROJECTS_LOADING: 'TOGGLE_FETCH_PROJECTS_LOADING',
	FETCH_PROJECT_DETAILS: 'FETCH_PROJECT_DETAILS',
	TOGGLE_FETCH_PROJECT_DETAILS_LOADING:
		'TOGGLE_FETCH_PROJECT_DETAILS_LOADING',
};
