export const requestActionTypes = {
	// Initiate fetching
	ADD_REQUEST_PHOTO_START: 'ADD_REQUEST_PHOTO_START',
	VALIDATE_REQUEST_PHOTO_START: 'VALIDATE_REQUEST_PHOTO_START',

	TOGGLE_ADD_REQUEST_PHOTO_LOADING: 'TOGGLE_ADD_REQUEST_PHOTO_LOADING',
	TOGGLE_VALIDATE_REQUEST_PHOTO_LOADING:
		'TOGGLE_VALIDATE_REQUEST_PHOTO_LOADING',
};
