export const feedbackActionTypes = {
	// Initiate fetching
	ADD_FEEDBACK_START: 'ADD_FEEDBACK_START',
	FETCH_FEEDBACK_START: 'FETCH_FEEDBACK_START',
	DELETE_FEEDBACK_START: 'DELETE_FEEDBACK_START',
	SET_FEEDBACKS: 'SET_FEEDBACKS',

	TOGGLE_ADD_FEEDBACK_LOADING: 'TOGGLE_ADD_FEEDBACK_LOADING',
	TOGGLE_FETCH_FEEDBACK_LOADING: 'TOGGLE_FETCH_FEEDBACK_LOADING',
	TOGGLE_DELETE_FEEDBACK_LOADING: 'TOGGLE_DELETE_FEEDBACK_LOADING',
};
