export const CityActionTypes = {
	FETCH_ALL_CITIES_START: 'FETCH_ALL_CITIES_START',
	SET_ALL_CITIES: 'SET_ALL_CITIES',
	FETCH_ALL_STATES_START: 'FETCH_ALL_STATES_START',
	SET_ALL_STATES: 'SET_ALL_STATES',
	SET_ERROR: 'SET_ERROR',
	TOGGLE_LOADING: 'TOGGLE_LOADING',
};
