export const PropertyActionTypes = {
	FETCH_PROPERTIES_RESOURCES_START: 'FETCH_PROPERTIES_RESOURCES_START',
	ADD_PROPERTY: 'ADD_PROPERTY',
	SET_FURNISHES: 'SET_FURNISHES',
	SET_AMENITIES: 'SET_AMENITIES',
	SET_ERROR: 'SET_ERROR',
	TOGGLE_LOADING: 'TOGGLE_LOADING',
};
